### ISSUE TITLE
Forge version

### ISSUE THREAD

**Issue by FullGreenGN** [Azuriom/AzLink#11]
Hello
Do you have an idea when AzLink for for can be release ?

**Comment by MrMicky-FR** [comment]
Hi, Forge support is not planned because multi-version support is really complicated with Forge and we won’t make 12 different versions for the 12 versions supported by AzLink on other platforms (currently 1.7.10 to 1.18). Also for modern Minecraft versions, you should use FabricMC (which may be supported in a future AzLink version if we have demand for it)
